version: '3'
services:
  api:
    build: docker/api
    expose:
      - 80
    ports:
      - 8080:80
    volumes:
      - ./src/api/:/var/www/app/
    working_dir: /var/www/app/
    links:
      - database

  textchannel:
    build: docker/textchannel
    tty: true
    volumes:
      - ./src/textchannel
    working_dir: /app
    links:
      - api

  web:
    build: docker/web
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./src/web/:/app/
    working_dir: /app/
    links:
      - api
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USERPOLLING=true

  database:
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "schedules"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
      TZ: "Asia/Tokyo"
    volumes:
      - ./volumes/mysql:/var/log/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARVITRARY=1
      - PMA_HOST=database
      - MPA_USER=dbuser
      - PMA_PASSWORD=dbpassword
    links:
      - database
    ports:
      - 8090:80
    volumes:
      - ./volumes/phpmyadmin:/sessions
